// Generated by scripts/sync-react-data.mjs from inkscape/hueprint_recipe_metadata.py.
export const recipeMetadata = [
  {
    "id": "none",
    "currentName": "No Recipe",
    "displayName": "Manual Palette",
    "category": "manual",
    "character": "Unstructured and user-directed.",
    "description": "Applies no predefined color relationship. Use the base color alone or build the palette manually."
  },
  {
    "id": "tonalFriends",
    "currentName": "Tonal Core",
    "displayName": "Essential Tonal",
    "category": "tonal",
    "character": "Compact, cohesive, and dependable.",
    "description": "Creates a compact family consisting of the base, a darker muted tone, and a lighter muted tone."
  },
  {
    "id": "quietMono",
    "currentName": "Quiet Mono",
    "displayName": "Soft Monochrome",
    "category": "tonal",
    "character": "Minimal, subdued, and tonally rich.",
    "description": "Generates a broad light-to-dark scale from the same hue while keeping saturation restrained."
  },
  {
    "id": "luxuryNeutral",
    "currentName": "Luxe Neutral",
    "displayName": "Refined Neutral",
    "category": "tonal",
    "character": "Elegant, understated, and composed.",
    "description": "Creates a restrained family of deep and pale low-saturation tones with subtle hue variation."
  },
  {
    "id": "mutedEditorial",
    "currentName": "Quiet Editorial",
    "displayName": "Restrained Editorial",
    "category": "tonal",
    "character": "Sophisticated, quiet, and content-first.",
    "description": "Builds a calm hierarchy of dark, light, and near-neutral tones with one subdued color variation."
  },
  {
    "id": "clayEarth",
    "currentName": "Clay Earth",
    "displayName": "Grounded Tones",
    "category": "tonal",
    "character": "Material, subdued, and organic.",
    "description": "Develops muted neighboring hues across light and dark values, producing a grounded tonal family."
  },
  {
    "id": "seededShades",
    "currentName": "Brand Shades",
    "displayName": "Extended Brand Scale",
    "category": "tonal",
    "character": "Versatile, cohesive, and expansive.",
    "description": "Develops dark, light, vivid, and softened versions of the base color into a flexible extended palette."
  },
  {
    "id": "richTonal",
    "currentName": "Rich Tonal",
    "displayName": "Rich Tonal",
    "category": "tonal",
    "character": "Deep, saturated, and cohesive.",
    "description": "Creates darker and lighter versions of the base while retaining more color intensity than a conventional tonal scale."
  },
  {
    "id": "dustAccent",
    "currentName": "Dusty Accent",
    "displayName": "Muted Highlight",
    "category": "accent",
    "character": "Quiet and selectively accented.",
    "description": "Builds a restrained tonal foundation and introduces one subdued secondary highlight."
  },
  {
    "id": "softDotAccent",
    "currentName": "Soft Accent Pair",
    "displayName": "Subtle Accent Pair",
    "category": "accent",
    "character": "Gentle, nuanced, and low-contrast.",
    "description": "Combines the base with a pale support tone and two closely related, softened accents."
  },
  {
    "id": "minimalAccent",
    "currentName": "Minimal Accent",
    "displayName": "Minimal Accent",
    "category": "accent",
    "character": "Clean, restrained, and precise.",
    "description": "Builds a mostly neutral tonal hierarchy and introduces one clear saturated accent."
  },
  {
    "id": "spotAccent",
    "currentName": "Signature Accent",
    "displayName": "Focused Accent",
    "category": "accent",
    "character": "Restrained with one decisive focal point.",
    "description": "Combines the base with pale tonal companions and one vivid contrasting focal color."
  },
  {
    "id": "trustSignal",
    "currentName": "Trust Signal",
    "displayName": "Trust Signal",
    "category": "accent",
    "character": "Stable, credible, and selectively assertive.",
    "description": "Combines a moderated base with stable dark and light support tones and one controlled vivid accent."
  },
  {
    "id": "neutralMatch",
    "currentName": "Balanced Accent",
    "displayName": "Structured Accent",
    "category": "accent",
    "character": "Balanced, practical, and controlled.",
    "description": "Adds dark and light tonal support plus two variations of a contrasting accent."
  },
  {
    "id": "monochromePlusAccent",
    "currentName": "Mono Accent",
    "displayName": "Mono Accent",
    "category": "accent",
    "character": "Disciplined and selectively expressive.",
    "description": "Creates a complete monochromatic hierarchy and adds one opposing signal color."
  },
  {
    "id": "brightSwitch",
    "currentName": "Bright Pivot",
    "displayName": "Vivid Pivot",
    "category": "accent",
    "character": "Clean, bright, and deliberately contrasting.",
    "description": "Pairs the base with pale supporting tones and two clearly differentiated accent colors."
  },
  {
    "id": "brightAccentPair",
    "currentName": "Bright Accent Pair",
    "displayName": "Bright Accent Pair",
    "category": "accent",
    "character": "Crisp, lively, and dual-accented.",
    "description": "Adds two vivid contrasting accents supported by a dark anchor and a pale neutral."
  },
  {
    "id": "softNatural",
    "currentName": "Organic Soft",
    "displayName": "Gentle Harmony",
    "category": "spectrum",
    "character": "Calm, soft, and approachable.",
    "description": "Surrounds the base with light, muted companions and a softly shifted secondary hue."
  },
  {
    "id": "warmHospitality",
    "currentName": "Welcoming Warmth",
    "displayName": "Soft Welcome",
    "category": "spectrum",
    "character": "Comfortable, human, and inviting.",
    "description": "Develops a range of lighter, softened hues with one deeper supporting tone."
  },
  {
    "id": "botanicalFresh",
    "currentName": "Botanical Fresh",
    "displayName": "Organic Range",
    "category": "spectrum",
    "character": "Fresh, varied, and naturally cohesive.",
    "description": "Moves through a related directional hue range with softened saturation and varied lightness."
  },
  {
    "id": "pastelBloom",
    "currentName": "Pastel Bloom",
    "displayName": "Airy Pastels",
    "category": "spectrum",
    "character": "Light, gentle, and optimistic.",
    "description": "Produces several light, low-saturation hues around the base with gentle color separation."
  },
  {
    "id": "coolArc",
    "currentName": "Cool Spectrum",
    "displayName": "Cohesive Spectrum",
    "category": "spectrum",
    "character": "Controlled, coordinated, and fluid.",
    "description": "Moves gradually through related hues while becoming slightly lighter and softer."
  },
  {
    "id": "gradientFriendly",
    "currentName": "Smooth Ramp",
    "displayName": "Progressive Ramp",
    "category": "spectrum",
    "character": "Continuous, directional, and transition-oriented.",
    "description": "Changes hue, lightness, and saturation in measured steps for smooth sequential transitions."
  },
  {
    "id": "warmArc",
    "currentName": "Warm Spectrum",
    "displayName": "Expansive Spectrum",
    "category": "spectrum",
    "character": "Broad, expressive, and progressive.",
    "description": "Extends the base through a wide hue progression that becomes lighter and softer."
  },
  {
    "id": "vividArc",
    "currentName": "Vivid Arc",
    "displayName": "Vivid Arc",
    "category": "spectrum",
    "character": "Fluid, colorful, and energetic.",
    "description": "Creates a high-chroma progression around the base rather than a muted directional spectrum."
  },
  {
    "id": "retroPop",
    "currentName": "Retro Pop",
    "displayName": "Eclectic Vintage",
    "category": "contrast",
    "character": "Nostalgic, unconventional, and playful.",
    "description": "Combines softened colors through broad, irregular hue and tonal shifts."
  },
  {
    "id": "friendlyContrast",
    "currentName": "Friendly Pop",
    "displayName": "Playful Contrast",
    "category": "contrast",
    "character": "Bright, optimistic, and approachable.",
    "description": "Combines a brighter base variation with two lively contrasting colors."
  },
  {
    "id": "threePointAccent",
    "currentName": "Triad Accent",
    "displayName": "Energetic Triad",
    "category": "harmony",
    "character": "Lively, varied, and chromatically distinct.",
    "description": "Adds two saturated hues in different directions from the base to create a distinct three-color palette."
  },
  {
    "id": "duotonePoster",
    "currentName": "Duotone Poster",
    "displayName": "Opposing Duotone",
    "category": "harmony",
    "character": "Bold, graphic, and polarized.",
    "description": "Pairs the base with its opposite hue and creates light and dark variations of both."
  },
  {
    "id": "directComplement",
    "currentName": "Direct Complement",
    "displayName": "Direct Complement",
    "category": "harmony",
    "character": "Classic, decisive, and focused.",
    "description": "Pairs the base with its direct opposite and adds tonal support for both sides of the relationship."
  },
  {
    "id": "splitComplement",
    "currentName": "Split Complement",
    "displayName": "Split Complement",
    "category": "harmony",
    "character": "Colorful, balanced, and less confrontational.",
    "description": "Adds the two hues adjacent to the opposite of the base, creating lively contrast with greater variety."
  },
  {
    "id": "doubleComplement",
    "currentName": "Double Complement",
    "displayName": "Double Complement",
    "category": "harmony",
    "character": "Rich, broad, and structured.",
    "description": "Combines two opposing hue pairs for a broader but still organized multicolor palette."
  },
  {
    "id": "complementaryBridge",
    "currentName": "Complementary Bridge",
    "displayName": "Complementary Bridge",
    "category": "harmony",
    "character": "Progressive, vivid, and tension-driven.",
    "description": "Moves through three colors surrounding the opposing hue rather than using one abrupt complement."
  },
  {
    "id": "boldPop",
    "currentName": "Pop System",
    "displayName": "High-Energy Mix",
    "category": "vibrant",
    "character": "Bold, saturated, and attention-seeking.",
    "description": "Combines the base with several highly saturated hues and one darker anchoring tone."
  },
  {
    "id": "vividAnalogous",
    "currentName": "Vivid Analogous",
    "displayName": "Vivid Analogous",
    "category": "vibrant",
    "character": "Energetic but cohesive.",
    "description": "Builds a lively family of neighboring hues that remain visibly related to the base."
  },
  {
    "id": "chromaticBurst",
    "currentName": "Chromatic Burst",
    "displayName": "Chromatic Burst",
    "category": "vibrant",
    "character": "Bold, varied, and celebratory.",
    "description": "Spreads vivid colors around the color wheel while retaining the selected base as the anchor."
  },
  {
    "id": "vividTriad",
    "currentName": "Vivid Triad",
    "displayName": "Vivid Triad",
    "category": "vibrant",
    "character": "Balanced, saturated, and dynamic.",
    "description": "Creates three lively color families distributed evenly around the color wheel."
  },
  {
    "id": "highContrast",
    "currentName": "Sharp Contrast",
    "displayName": "Sharp Contrast",
    "category": "contrast",
    "character": "Decisive, dramatic, and highly differentiated.",
    "description": "Combines extreme dark and light tones with a vivid opposing hue for maximum separation."
  },
  {
    "id": "vividCounterpoint",
    "currentName": "Vivid Counterpoint",
    "displayName": "Vivid Counterpoint",
    "category": "contrast",
    "character": "Clean, opposing, and assertive.",
    "description": "Pairs the base with a vivid opposing hue and anchors both with dark and light supporting colors."
  },
  {
    "id": "editorialContrast",
    "currentName": "Magazine Contrast",
    "displayName": "Editorial Hierarchy",
    "category": "systems",
    "character": "Structured, authoritative, and content-led.",
    "description": "Builds a strong dark-to-light hierarchy and introduces two related accent roles."
  },
  {
    "id": "cleanUi",
    "currentName": "Interface Kit",
    "displayName": "Interface Essentials",
    "category": "systems",
    "character": "Functional, neutral, and system-ready.",
    "description": "Generates distinct colors for primary emphasis, pale surfaces, dark content, and secondary accents."
  },
  {
    "id": "signalSystem",
    "currentName": "Signal System",
    "displayName": "Multi-Signal System",
    "category": "systems",
    "character": "Informational, systematic, and multifunctional.",
    "description": "Combines a stable tonal foundation with two vivid accents for clearly differentiated signals."
  },
  {
    "id": "lightInterfaceSignals",
    "currentName": "Light Interface Signals",
    "displayName": "Light Interface Signals",
    "category": "systems",
    "character": "Clean, bright, and functional.",
    "description": "Creates light surfaces, dark content, a primary color, and two lively signal colors."
  },
  {
    "id": "categoricalFive",
    "currentName": "Categorical Five",
    "displayName": "Categorical Five",
    "category": "systems",
    "character": "Distinct, balanced, and data-ready.",
    "description": "Produces five clearly separated colors for categories, series, diagrams, or repeated components."
  },
  {
    "id": "techDigital",
    "currentName": "Digital Pulse",
    "displayName": "Electric Interface",
    "category": "darkLuminous",
    "character": "Futuristic, sharp, and digitally energetic.",
    "description": "Builds a dark digital foundation with a vivid contrasting accent and lighter supporting colors."
  },
  {
    "id": "nightMode",
    "currentName": "Night Mode",
    "displayName": "Dark Interface",
    "category": "darkLuminous",
    "character": "Immersive, luminous, and screen-focused.",
    "description": "Adds deep surface colors and brighter accents intended to remain distinct in dark environments."
  },
  {
    "id": "midnightComplement",
    "currentName": "Midnight Complement",
    "displayName": "Midnight Complement",
    "category": "darkLuminous",
    "character": "Dark, focused, and luminous.",
    "description": "Combines two dark surfaces, the base, and one vivid complementary accent."
  },
  {
    "id": "darkWarmSignals",
    "currentName": "Dark Warm Signals",
    "displayName": "Dark Warm Signals",
    "category": "darkLuminous",
    "character": "Dark, energetic, and warm-accented.",
    "description": "Creates dark surfaces with lively yellow, orange, and red signal colors alongside the selected base."
  },
  {
    "id": "darkCoolSignals",
    "currentName": "Dark Cool Signals",
    "displayName": "Dark Cool Signals",
    "category": "darkLuminous",
    "character": "Dark, electric, and cool-accented.",
    "description": "Creates dark surfaces with cyan, violet, and magenta accents alongside the selected base."
  },
  {
    "id": "neonTriad",
    "currentName": "Neon Triad",
    "displayName": "Neon Triad",
    "category": "darkLuminous",
    "character": "Dark, vivid, and multichromatic.",
    "description": "Places the base and two vivid triadic accents against a dark surface system."
  },
  {
    "id": "warmAccents",
    "currentName": "Warm Accents",
    "displayName": "Warm Accents",
    "category": "temperature",
    "character": "Sunny, energetic, and inviting.",
    "description": "Keeps the selected base and introduces vivid yellow, orange, and red accent options."
  },
  {
    "id": "coolAccents",
    "currentName": "Cool Accents",
    "displayName": "Cool Accents",
    "category": "temperature",
    "character": "Crisp, technical, and luminous.",
    "description": "Keeps the selected base and introduces cyan, violet, and magenta accent options."
  },
  {
    "id": "warmCoolSplit",
    "currentName": "Warm-Cool Split",
    "displayName": "Warm-Cool Split",
    "category": "temperature",
    "character": "Balanced, contrasting, and versatile.",
    "description": "Combines warm and cool accents around the selected base without committing to one temperature family."
  },
  {
    "id": "backgroundPop",
    "currentName": "Background Pop",
    "displayName": "Background Pop",
    "category": "background",
    "character": "Adaptive, crisp, and foreground-first.",
    "description": "Treats the selected color as a background and generates adaptive dark-or-light foregrounds plus vivid contrasting accents that stand clearly against it."
  },
  {
    "id": "darkBackdropPunch",
    "currentName": "Dark Backdrop Punch",
    "displayName": "Dark Backdrop Punch",
    "category": "background",
    "character": "Nocturnal, luminous, and high-impact.",
    "description": "Builds bright neutral and neon-like companions intended to flare against a dark selected background."
  },
  {
    "id": "lightBackdropPunch",
    "currentName": "Light Backdrop Punch",
    "displayName": "Light Backdrop Punch",
    "category": "background",
    "character": "Graphic, saturated, and ink-forward.",
    "description": "Pairs a light selected background with deep text and forceful cobalt, coral, and violet foreground colors."
  },
  {
    "id": "electricForeground",
    "currentName": "Electric Foreground",
    "displayName": "Electric Foreground",
    "category": "background",
    "character": "Charged, legible, and multichromatic.",
    "description": "Adds an adaptive foreground hierarchy and electric lime, cyan, and magenta signals around the selected background."
  },
  {
    "id": "posterOnColor",
    "currentName": "Poster on Color",
    "displayName": "Poster on Color",
    "category": "background",
    "character": "Bold, editorial, and display-oriented.",
    "description": "Creates decisive foreground and supporting colors for typography, icons, and graphic shapes placed over a colored field."
  },
  {
    "id": "spotlightContrast",
    "currentName": "Chromatic Spotlight",
    "displayName": "Chromatic Spotlight",
    "category": "background",
    "character": "Focused, theatrical, and attention-directing.",
    "description": "Uses adaptive text values with vivid shifted highlights to produce clear focal points over the selected background."
  },
  {
    "id": "acidCabaret",
    "currentName": "Acid Cabaret",
    "displayName": "Acid Cabaret",
    "category": "daring",
    "character": "Fluorescent, decadent, and unapologetic.",
    "description": "Collides hot magenta, acid green, cyan, and deep plum around the base for an extravagant high-energy palette."
  },
  {
    "id": "tropicalVoltage",
    "currentName": "Tropical Voltage",
    "displayName": "Tropical Voltage",
    "category": "daring",
    "character": "Sun-soaked, electric, and exuberant.",
    "description": "Combines charged coral, chartreuse, cyan, and ultraviolet for tropical color with deliberately amplified tension."
  },
  {
    "id": "ultravioletCitrus",
    "currentName": "Ultraviolet Citrus",
    "displayName": "Ultraviolet Citrus",
    "category": "daring",
    "character": "Sharp, surreal, and flavorfully discordant.",
    "description": "Sets ultraviolet and citrus tones against coral, cyan, and an adaptive neutral to create a vivid surrealist clash."
  },
  {
    "id": "coralCobaltClash",
    "currentName": "Coral–Cobalt Clash",
    "displayName": "Coral–Cobalt Clash",
    "category": "daring",
    "character": "Graphic, fashion-forward, and polarized.",
    "description": "Opposes hot coral and saturated cobalt, then intensifies the composition with chartreuse, magenta, and a pale flash."
  },
  {
    "id": "cyberBazaar",
    "currentName": "Cyber Bazaar",
    "displayName": "Cyber Bazaar",
    "category": "daring",
    "character": "Digital, exotic, and densely colorful.",
    "description": "Mixes turquoise, orchid, saffron, vermilion, and deep violet into a crowded but deliberately controlled chromatic market."
  },
  {
    "id": "carnivalClash",
    "currentName": "Carnival Clash",
    "displayName": "Carnival Clash",
    "category": "daring",
    "character": "Festive, brash, and rhythmically varied.",
    "description": "Combines red, gold, green, blue, and purple at vivid strengths for celebratory palettes that refuse to recede."
  },
  {
    "id": "semanticCore",
    "currentName": "Semantic Core",
    "displayName": "Semantic Core",
    "category": "semantic",
    "character": "Universal, functional, and brand-aware.",
    "description": "Keeps the selected base and adds conventional information, success, warning, error, and adaptive text colors."
  },
  {
    "id": "semanticLight",
    "currentName": "Semantic on Light",
    "displayName": "Semantic on Light",
    "category": "semantic",
    "character": "Clear, production-ready, and light-surface oriented.",
    "description": "Provides light surfaces, dark text, and recognizable information, success, warning, and error roles alongside the base."
  },
  {
    "id": "semanticDark",
    "currentName": "Semantic on Dark",
    "displayName": "Semantic on Dark",
    "category": "semantic",
    "character": "Luminous, functional, and dark-surface oriented.",
    "description": "Provides dark surfaces, pale text, and brighter semantic signals designed to remain distinct in dark interfaces."
  },
  {
    "id": "financialSignals",
    "currentName": "Financial Signals",
    "displayName": "Financial Signals",
    "category": "semantic",
    "character": "Directional, analytical, and immediately readable.",
    "description": "Adds positive, negative, caution, neutral, and informational roles for financial dashboards, tables, and reporting."
  },
  {
    "id": "dataStates",
    "currentName": "Data States",
    "displayName": "Data States",
    "category": "semantic",
    "character": "Systematic, categorical, and state-aware.",
    "description": "Creates information, success, warning, error, inactive, and selected-state colors for interfaces and data visualization."
  },
  {
    "id": "editorialStates",
    "currentName": "Editorial States",
    "displayName": "Editorial States",
    "category": "semantic",
    "character": "Workflow-oriented, expressive, and precise.",
    "description": "Maps approved, review, revision, rejected, annotation, and text roles for editorial and collaborative workflows."
  }
] as const;
